apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: governance-policy-framework-addon-dfsa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:8d9826a1a5a2e38651670c125555fbd02a77ba07ed9d7b27de91d8f857a018d1
        name: container-image
        resources: {}
status: {}
