apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: governance-policy-framework-addon-dfsa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: governance-policy-framework-addon-dfsa
    app.kubernetes.io/part-of: governance-policy-framework-addon
  name: governance-policy-framework-addon-dfsa
  namespace: red-hat-acm-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: governance-policy-framework-addon-dfsa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: governance-policy-framework-addon-dfsa
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:1ae5be2f28517ac7fe464a84d0d04c1886b846bc3990438901906b49296458f1
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
