apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: governance-policy-framework-addon-dfsa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: governance-policy-framework-addon-dfsa
    app.kubernetes.io/part-of: governance-policy-framework-addon
  name: governance-policy-framework-addon-dfsa
  namespace: red-hat-acm-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: governance-policy-framework-addon-dfsa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: governance-policy-framework-addon-dfsa
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:8d9826a1a5a2e38651670c125555fbd02a77ba07ed9d7b27de91d8f857a018d1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
